from fastapi import FastAPI
from fastapi.responses import JSONResponse
from Standard_Visualization_Service import Standard_Visualization_Service

app1 = FastAPI()

svs = Standard_Visualization_Service()

# @app.get("/")
# async def root():
#     return {"message": "Welcome to the Standard Visualization Service"}

# @app.get("/data")
# async def get_data():
#     data = svs.df.to_json(orient='records', date_format='iso')
#     return JSONResponse(content=data)


prompt = """
You have a dataset df with columns (Note- don't use any csv we already have database use that database df).
1. Before visualization make sure data is clean
2. Give me cluster column chart for leadStatus and createdAt but only take Opportunity, Warm Lead, Cold Lead, and Visited categories from leadStatus using Plotly for dynamic visualization.
3. Display Stacked bar chart for techStack and classMode using Plotly for dynamic visualization.
4. Give stacked bar chart for leadStatus and leadSource using Plotly for dynamic visualization.
5. Need a Horizontal bar chart for leadSource to count the number of leads generated by the leadSource mention leadSource in y-axis using Plotly for dynamic visualization.
Ensure each plot has titles, labels, colors, and borders to enhance clarity and aesthetics. Utilize a white template for the plots.
Provide only code without comments or instructions.
Save all these dynamic visualizations as a file or supported format with the following names:
- cluster_column_chart.html
- stacked_bar_chart_techstack_classmode.html
- stacked_bar_chart_leadstatus_leadsource.html
- horizontal_bar_chart.html
Display in web browser. Note: The dataset df is already defined and available for use.
"""
@app1.get("/")
async def root():
    svs.process_visualization_code(prompt, file_name='visualization_code.py')
    return {"message": "Welcome to the Standard Visualization Service"}
@app1.get("/First_visualization")
async def open_html_file_one():
    # svs.process_visualization_code(prompt, file_name='visualization_code.py')
    file_name_1 = "D:\\DigitalLync\\Visualizations\\horizontal_bar_chart.html"
    return svs.open_html_file_one(file_name_1)
# @app1.get("/hello")
# async def process_visualization_code(self, prompt:str, file_name):
#     return svs.process_visualization_code(prompt, 'visualization_code.py')
@app1.get("/Second_visualization")
async def open_html_file_two():
    file_name_2 = "D:\\DigitalLync\\Visualizations\\stacked_bar_chart_leadstatus_leadsource.html"
    return svs.open_html_file_two(file_name_2)
@app1.get("/Third_visualization")
async def open_html_file_three():
    file_name_3 = "D:\\DigitalLync\\Visualizations\\cluster_column_chart.html"
    return svs.open_html_file_three(file_name_3)
@app1.get("/Fourth_visualization")
async def open_html_file_four():
    file_name_4 = "D:\\DigitalLync\\Visualizations\\stacked_bar_chart_techstack_classmode.html"
    return svs.open_html_file_four(file_name_4)










